# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jddj # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-beijing # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: #触发器
    - timer:
        parameters:
          name: fruit
          cronExpression: "0 10 0,8,11,17 * * * *"
          enable: true
          argument: jddj_fruit
    - timer:
        parameters:
          name: bean
          cronExpression: "0 0 8 * * * *"
          enable: true
          argument: jddj_bean
    - timer:
        parameters:
          name: plantBeans
          cronExpression: "0 0 9 * * * *"
          enable: true
          argument: jddj_plantBeans
    - timer:
        parameters:
          name: getPoints_0
          cronExpression: "0 0-25/5 0 * * * *"
          enable: true
          argument: jddj_getPoints
    - timer:
        parameters:
          name: getPoints_1
          cronExpression: "0 25 5-20/5 * * * *"
          enable: true
          argument: jddj_getPoints
    - timer:
        parameters:
          name: fruit_collectWater
          cronExpression: "0 5 */2 * * * *"
          enable: true
          argument: jddj_fruit_collectWater
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的